name: CD

on:
  push:
      branches:
          - development
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout development branch
              uses: actions/checkout@v2
              with:
                  ref: development
                  token: ${{secrets.GITHUB_TOKEN}}
                  fetch-depth: 0

            - name: Push changes to master branch
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{secrets.GITHUB_TOKEN}}
                  force: true
