name: CI

on: 
  push:
    branches:    
      - test

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v1
            - name: Using Node.js version ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}

            - name: run npm install
              run: |
                  npm install
            - name: run npm test
              run: |
                  npm test

