name: CI

on:
  pull_request:
      branches: [development]
      types: [opened, synchronize]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout request branch
              uses: actions/checkout@v2
              with:
                  ref: ${{github.event.pull_request.head.sha}}

            - name: Run npm install
              run: |
                  npm install

            - name: Run npm test
              run: |
                  npm test


